PufferFinance/puffer-sdk

lib/contracts/addresses.ts, lib/contracts/handlers/erc20-permit-handler.ts, lib/contracts/handlers/puf-locker-handler.test.ts, lib/contracts/handlers/puf-locker-handler.ts, lib/contracts/handlers/puffer-l2-depositor-handler.test.ts, lib/contracts/handlers/puffer-l2-depositor-handler.ts, lib/contracts/tokens.ts
The previous PR #23 was not merged to main.
=> 1802: Update contract addresses, token permit versions and add pre-approved token deposit to PufLocker

lib/contracts/addresses.ts, lib/contracts/handlers/erc20-permit-handler.ts, lib/contracts/handlers/puf-locker-handler.test.ts, lib/contracts/handlers/puf-locker-handler.ts, lib/contracts/handlers/puf-token-handler.test.ts, lib/contracts/handlers/puf-token-handler.ts, lib/contracts/handlers/puffer-depositor-handler.ts, lib/contracts/handlers/puffer-l2-depositor-handler.ts, lib/contracts/handlers/puffer-vault-handler.ts, lib/contracts/tokens.ts
This makes it easier to work with the SDK.
=> 1907: Handle tokens and puf tokens separately

.github/workflows/build-and-test.yml, docs/package.json, package.json, pnpm-lock.yaml
Follow up of #31 as that did not work.
=> Fix docs and update all packages

lib/contracts/tokens.ts
Adds PUFFER and CARROT token so it can be used by apps.
=> AB#3120: Add PUFFER and CARROT tokens

lib/contracts/tokens.ts
=> AB#3164: New tokens

lib/contracts/addresses.ts
The contract is updated from Nucleus.
[AB#3309](https://dev.azure.com/pufferfi/7ec516e5-cd36-448b-914b-0ffdf2fabd74/_workitems/edit/3309)
=> AB#3309: Update nucleus atomic queue contract address

lib/api/puffer-client.ts, lib/contracts/abis/mainnet/Distributor.ts, lib/contracts/addresses.ts, lib/contracts/handlers/distributor-handler.test.ts, lib/contracts/handlers/distributor-handler.ts, lib/main.ts
Adds a handler and the ABI for Merkle/Angle distributor contract, which will be used to claim carrot rewards via the UI
=> 3365 Distributor handler

package.json, pnpm-lock.yaml
Update dependencies to latest, should fix some dependabot high and critical issues
=> Update dependencies to latest, should fix some dependabot high and critical issues

lib/contracts/tokens.ts
Add more pufETH and xPufETH addresses
=> Add pufETH/xPufETH addresses for more chains

lib/contracts/abis/mainnet/PufferVaultV2.ts, lib/contracts/handlers/__tests__/puffer-vault-handler.test.ts, lib/contracts/handlers/puffer-vault-handler.ts
3459 add deposit fn to puffer vault
- update abi
- update tests
=> 3459 add deposit fn to puffer vault handler

lib/contracts/tokens.ts
- just adding vePUFFER address
=> Add vePUFFER address

lib/chains/constants.ts, lib/contracts/tokens.ts
=> AB#3557: Add mainnet address for xPufETH

lib/chains/constants.ts
=> Add berachain

lib/contracts/tokens.ts
=> AB#3615: Add TAC pufETH token

lib/contracts/abis/mainnet/ConcreteMultiStrategyVault.ts, lib/contracts/handlers/__tests__/concrete-vault-handler.test.ts, lib/contracts/handlers/concrete-vault-handler.ts
[AB#3615](https://dev.azure.com/pufferfi/7ec516e5-cd36-448b-914b-0ffdf2fabd74/_workitems/edit/3615)
=> AB#3615: Add previewRedeem function to concrete vault contract

lib/contracts/handlers/__tests__/validator-ticket-handler.test.ts, lib/contracts/handlers/validator-ticket-handler.ts
Made an error converting one function from the ABI...
=> Add payableAmount to purchaseValidatorTicket in handler

lib/contracts/tokens.ts
=> AB#3928: Add WETH address for hoodi

lib/contracts/handlers/__tests__/institutional-vault-handler.test.ts, lib/contracts/handlers/institutional-vault-handler.ts
=> AB#3939: Add customExternalCall to institutional vault

lib/contracts/abis/mainnet/InstitutionalVault.ts, lib/contracts/handlers/__tests__/institutional-vault-handler.test.ts, lib/contracts/handlers/institutional-vault-handler.ts
- add missing arguments & SC functions to SDK for starting validators
=> pass amounts to start validators sc call & abi

lib/contracts/abis/mainnet/InstitutionalVault.ts, lib/contracts/handlers/__tests__/institutional-vault-handler.test.ts, lib/contracts/handlers/institutional-vault-handler.ts
Add requestEigenPodConsolidation function to InstitutionalVault
=> Add requestEigenPodConsolidation function to InstitutionalVault

lib/contracts/handlers/__tests__/institutional-vault-handler.test.ts, lib/contracts/handlers/institutional-vault-handler.ts
- add a value param so we can pass a small amount of ETH otherwise tx will fail.
=> Add value param to requestEigenPodConsolidation

lib/contracts/handlers/__tests__/lagoon-vault-handler.test.ts, lib/contracts/handlers/lagoon-vault-handler.ts
[AB#3839](https://dev.azure.com/pufferfi/7ec516e5-cd36-448b-914b-0ffdf2fabd74/_workitems/edit/3839)
=> AB#3839: Add convert functions for LagoonVault

lib/contracts/addresses.ts, lib/contracts/tokens.ts
=> Update GaugeRegsitry address to mainnet
